"""Attach `source` locators to trace files written before trace enrichment.

The pipeline stamps every trace entry with a `source` dict (which artefact the
link points into, where in it, and whether it resolved) via
``Base._enrich_trace_entries`` -> ``_trace_source_for_entry``. Artefacts
generated before that feature landed carry no `source` at all, so the
traceability gate reports them as unresolved and the resolvability metric has
nothing to read.

This tool applies exactly the same locator logic to trace files that already
exist, so archived artefacts gain the field they would have had if generated by
the current pipeline. It is *enrichment*, not regeneration: no model is called
and no artefact content is altered — only the `source` key is added to trace
entries, plus (optionally) the concept tag rename described below.

What it reproduces, per layer, matching each phase's own hook:

    concept    element = Instance or Concept, located in the REQUIREMENT text
               (character span), file label `requirement:<gid as written>`
    notation   element = Emfatic_class, located in the Emfatic artefact (line)
    model      element = Model_Element_id or Model_Element, in the EOL program
    behaviour  element = transition, located in the RoboChart artefact

The concept phase's trace tag was renamed `req` -> `term_trace`; a current run
writes `term_trace`, so `--rename-legacy-tag` (default on) normalises it. Pass
`--keep-legacy-tag` to leave it.

Dry run by default; pass --write to modify files in place.

    python MALCOMp/enrich_traces.py                     # report what would change
    python MALCOMp/enrich_traces.py --write             # apply
    python MALCOMp/enrich_traces.py --root case_studies/auv/fixtures --write
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import trace_locator  # noqa: E402

logger = logging.getLogger("enrich_traces")

REPO_ROOT = Path(__file__).resolve().parent.parent

# (trace filenames, tag, legacy tags, artefact candidates, locator kind,
#  element fields, char-span?). Artefact candidates cover both the run-directory
#  names and the config's code_file names for the same artefact.
LAYERS = (
    dict(layer="concept",
         trace=("result_term_extraction.json", "result_concept_trace.json"),
         tag="term_trace", legacy=("req",),
         artefact=(), kind="requirement",
         elements=("Instance", "Concept"), char=True),
    dict(layer="notation",
         trace=("result_dsl_extraction.json", "result_dsml_trace.json"),
         tag="dsl_trace", legacy=(),
         artefact=("result_DSL.emf", "result_dsml.emf"), kind="emfatic",
         elements=("Emfatic_class",), char=False),
    dict(layer="model",
         trace=("result_model_creation.json", "result_model_trace.json"),
         tag="model_trace", legacy=(),
         artefact=("result_eol_program.eol", "result_model.eol"), kind="eol",
         elements=("Model_Element_id", "Model_Element"), char=False),
    dict(layer="behaviour",
         trace=("result_statemachine_extraction.json",
                "result_behaviour_trace.json"),
         tag="stm_trace", legacy=(),
         artefact=("STM.txt", "result_behaviour_complete.rct",
                   "result_behaviour_model.rct"), kind="robochart",
         elements=("transition",), char=False),
)


def canonical_gid(value) -> str:
    return re.sub(r"[^0-9a-z]", "", str(value or "").lower())


def build_source(file_label: str, span, char: bool = False) -> dict:
    """Identical to ``Base._build_source`` — keep the shapes in step."""
    if span is None:
        return {"file": file_label, "resolved": False}
    start, end = span
    if char:
        return {"file": file_label, "char_start": start,
                "char_end": end, "resolved": True}
    return {"file": file_label, "line_start": start,
            "line_end": end, "resolved": True}


def load_requirements(case_dir: Path) -> dict:
    """{canonical gid: description} for the case study's requirement set."""
    out: dict[str, str] = {}
    for path in sorted((case_dir / "requirements").glob("requirement_*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            logger.warning("skipping unreadable %s", path.name)
            continue
        items = data.get("requirements") if isinstance(data, dict) else data
        for r in items or []:
            if isinstance(r, dict):
                gid = canonical_gid(r.get("id") or r.get("gid") or r.get("GID"))
                if gid and gid not in out:
                    out[gid] = r.get("description", "")
    return out


def _first_existing(root: Path, names):
    for n in names:
        p = root / n
        if p.is_file():
            return p
    return None


def enrich_file(trace_path: Path, spec: dict, requirements: dict,
                rename_legacy: bool = True) -> dict:
    """Compute `source` for every entry in one trace file.

    Returns a report dict; the file is not written here.
    """
    rep = dict(layer=spec["layer"], path=trace_path, entries=0, resolved=0,
               unresolved=0, already=0, artefact="", renamed_from="",
               data=None, tag=spec["tag"], changed=False, skipped="")
    try:
        data = json.loads(trace_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as ex:
        rep["skipped"] = f"unreadable: {ex}"
        return rep
    if not isinstance(data, dict):
        rep["skipped"] = "not an object"
        return rep

    tag = spec["tag"]
    if not isinstance(data.get(tag), list):
        for old in spec["legacy"]:
            if isinstance(data.get(old), list):
                rep["renamed_from"] = old
                tag = old
                break
        else:
            rep["skipped"] = f"no {spec['tag']!r} array"
            return rep

    artefact_text = ""
    if spec["artefact"]:
        artefact = _first_existing(trace_path.parent, spec["artefact"])
        if artefact is None:
            rep["skipped"] = ("target artefact missing ("
                              + "/".join(spec["artefact"]) + ")")
            return rep
        rep["artefact"] = artefact.name
        artefact_text = artefact.read_text(encoding="utf-8", errors="replace")
    else:
        rep["artefact"] = "requirement text"

    for entry in data[tag]:
        if not isinstance(entry, dict):
            continue
        rep["entries"] += 1
        if isinstance((entry.get("source") or {}).get("resolved"), bool):
            rep["already"] += 1
        gid_raw = entry.get("requirement_gid") or entry.get("GID") or entry.get("gid")
        element = next((entry[f] for f in spec["elements"]
                        if entry.get(f) not in (None, "", [])), None)

        if spec["kind"] == "requirement":
            file_label = f"requirement:{gid_raw}"
            text = requirements.get(canonical_gid(gid_raw), "")
        else:
            file_label = rep["artefact"]
            text = artefact_text

        span = None
        if element is not None and text:
            span = trace_locator.locate(spec["kind"], str(element), text)
        entry["source"] = build_source(file_label, span, char=spec["char"])
        if span is None:
            rep["unresolved"] += 1
        else:
            rep["resolved"] += 1

    if rep["renamed_from"] and rename_legacy:
        data[spec["tag"]] = data.pop(rep["renamed_from"])
        rep["tag"] = spec["tag"]
    else:
        rep["tag"] = tag
    rep["data"] = data
    rep["changed"] = bool(rep["entries"]) or bool(
        rep["renamed_from"] and rename_legacy)
    return rep


def rebuild_concept_model(trace_path: Path, write: bool = False) -> dict:
    """Reconstruct phase 2's concept-model artefact from its trace file.

    `result_concept_model.json` is the deduplicated Concepts and Instances of
    the concept trace, derived **deterministically** by
    ``ConceptExtraction._store_concept_model`` — no model call is involved. It
    is nonetheless a generated output that was never committed, so phases 3-5,
    which load it as a prompt asset, cannot be constructed in a fresh checkout.

    Rather than reimplement the dedup (which would drift), this calls the phase
    method itself on an object carrying only the two attributes it touches.
    """
    rep = dict(path=trace_path, concepts=0, instances=0, out=None, skipped="")
    try:
        data = json.loads(trace_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as ex:
        rep["skipped"] = f"unreadable: {ex}"
        return rep
    entries = None
    for tag in ("term_trace", "req"):
        if isinstance(data.get(tag), list):
            entries = data[tag]
            break
    if entries is None:
        rep["skipped"] = "no concept trace array"
        return rep

    from phases.concept import ConceptExtraction

    class _Shim:
        """Carries only what _store_concept_model reads: stage_config and
        output_dir. Constructing the real stage would build LLM agents."""

        def __init__(self, output_dir: Path):
            self.output_dir = output_dir
            self.stage_config = {"output": {"code_file": "result_concept_model.json"}}

        def _record_artifact(self, path):    # no manifest outside a real run
            pass

    shim = _Shim(trace_path.parent)
    ConceptExtraction._store_concept_model(shim, entries)
    out = trace_path.parent / "result_concept_model.json"
    model = json.loads(out.read_text(encoding="utf-8"))
    rep.update(concepts=len(model["concepts"]), instances=len(model["instances"]),
               out=out)
    if not write:
        out.unlink()          # dry run: leave the tree untouched
        rep["out"] = None
    return rep


def discover(root: Path) -> list[tuple[Path, dict]]:
    """(trace file, layer spec) pairs under `root`, including `root` itself."""
    dirs = [root] + [p for p in sorted(root.rglob("*")) if p.is_dir()]
    found = []
    for d in dirs:
        for spec in LAYERS:
            p = _first_existing(d, spec["trace"])
            if p is not None:
                found.append((p, spec))
    return found


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=str(REPO_ROOT / "case_studies" / "auv"),
                    help="directory tree to scan for trace files")
    ap.add_argument("--case-dir", default=None,
                    help="case study holding requirements/ (default: --root, "
                         "or its nearest ancestor containing requirements/)")
    ap.add_argument("--write", action="store_true",
                    help="modify files in place (default: dry run)")
    ap.add_argument("--keep-legacy-tag", action="store_true",
                    help="do not rename the concept tag req -> term_trace")
    ap.add_argument("--no-concept-model", action="store_true",
                    help="skip reconstructing result_concept_model.json")
    args = ap.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    root = Path(args.root).resolve()
    if not root.is_dir():
        raise SystemExit(f"not a directory: {root}")

    case_dir = Path(args.case_dir).resolve() if args.case_dir else None
    if case_dir is None:
        for cand in [root, *root.parents]:
            if (cand / "requirements").is_dir():
                case_dir = cand
                break
    if case_dir is None:
        raise SystemExit("could not find a requirements/ directory; pass --case-dir")
    requirements = load_requirements(case_dir)
    if not requirements:
        raise SystemExit(f"no requirements under {case_dir / 'requirements'}")

    targets = discover(root)
    if not targets:
        raise SystemExit(f"no trace files under {root}")

    print(f"requirements: {len(requirements)} (from {case_dir.name}/requirements)")
    print(f"trace files:  {len(targets)} under {root}")
    print(f"mode:         {'WRITE' if args.write else 'dry run'}\n")

    totals = dict(entries=0, resolved=0, unresolved=0, already=0, files=0)
    for path, spec in targets:
        rep = enrich_file(path, spec, requirements,
                          rename_legacy=not args.keep_legacy_tag)
        rel = path.relative_to(root) if path.is_relative_to(root) else path
        if rep["skipped"]:
            print(f"  skip  {rel}  ({rep['skipped']})")
            continue
        note = []
        if rep["renamed_from"]:
            note.append(f"tag {rep['renamed_from']!r}->{rep['tag']!r}"
                        if not args.keep_legacy_tag
                        else f"legacy tag {rep['renamed_from']!r} kept")
        if rep["already"]:
            note.append(f"{rep['already']} already had source")
        pct = (rep["resolved"] / rep["entries"]) if rep["entries"] else 0
        print(f"  {'write' if args.write else 'would'} {rel}  "
              f"[{rep['layer']}] {rep['entries']} entries -> "
              f"{rep['resolved']} resolved / {rep['unresolved']} unresolved "
              f"({pct:.0%}) vs {rep['artefact']}"
              + ("  | " + "; ".join(note) if note else ""))
        if args.write and rep["changed"]:
            path.write_text(json.dumps(rep["data"], indent=4,
                                       ensure_ascii=False) + "\n",
                            encoding="utf-8")
        totals["files"] += 1
        for k in ("entries", "resolved", "unresolved", "already"):
            totals[k] += rep[k]

    if not args.no_concept_model:
        print()
        for path, spec in targets:
            if spec["layer"] != "concept":
                continue
            rep = rebuild_concept_model(path, write=args.write)
            rel = (path.parent.relative_to(root)
                   if path.parent.is_relative_to(root) else path.parent)
            if rep["skipped"]:
                print(f"  skip  {rel}/result_concept_model.json ({rep['skipped']})")
            else:
                print(f"  {'write' if args.write else 'would'} "
                      f"{rel}/result_concept_model.json  "
                      f"[concept model] {rep['concepts']} concepts, "
                      f"{rep['instances']} instances (derived from the trace)")

    print(f"\n{totals['files']} files, {totals['entries']} entries: "
          f"{totals['resolved']} resolved, {totals['unresolved']} unresolved"
          f" ({totals['already']} already carried a source field)")
    if not args.write:
        print("dry run — nothing written; pass --write to apply")
    return 0


if __name__ == "__main__":
    sys.exit(main())
